<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="nikunj-20h1cto1ww" failures="1" tests="9" name="Default test" time="0.086" errors="0" timestamp="2021-01-15T04:10:08 IST">
  <testcase classname="TestCalculate" name="AllowingMultipleDelimiters" time="0.007">
    <failure type="java.lang.NumberFormatException" message="For input string: &amp;quot;1*2%3&amp;quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: "1*2%3"
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
at java.base/java.lang.Integer.parseInt(Integer.java:652)
at java.base/java.lang.Integer.parseInt(Integer.java:770)
at Calculator.CheckforNegatives(Calculator.java:58)
at Calculator.CalculateSum(Calculator.java:39)
at Calculator.calculate(Calculator.java:25)
at TestCalculate.AllowingMultipleDelimiters(TestCalculate.java:63)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- AllowingMultipleDelimiters -->
  <testcase classname="TestCalculate" name="DelimitersofVariableLength" time="0.004"/>
  <testcase classname="TestCalculate" name="EmptyStringReturnZero" time="0.001"/>
  <testcase classname="TestCalculate" name="ReturnSumofThreeNumberWithCommaAndNewLineDelimiter" time="0.001"/>
  <testcase classname="TestCalculate" name="ReturnSumofTwoNumberWithCommaDelimiter" time="0.001"/>
  <testcase classname="TestCalculate" name="ReturnSumofTwoNumberWithNewLineDelimiter" time="0.002"/>
  <testcase classname="TestCalculate" name="StringWithSingleNumber" time="0.001"/>
  <testcase classname="TestCalculate" name="StringWithnegativeNumberReturnsException" time="0.002"/>
  <testcase classname="TestCalculate" name="ValuesGreaterThan1000AreIgnored" time="0.001"/>
</testsuite> <!-- Default test -->
